spring.profiles.active: develop
server:
  port: 8090
---
spring:
  config:
    activate:
      on-profile: develop
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/cmm
    username: user1
    password: user1
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false