spring.profiles.active: develop
server:
  port: 8090
---
spring:
  config:
    activate:
      on-profile: develop
  jpa:
    show_sql: true
  datasource:
    url: jdbc:mysql://user1:user1@localhost:3306/cmm
    initialize: false
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false